name: Resharper Analysis

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main


jobs:
  resharper-analysis:
    name: Resharper Analysis
    runs-on: ${{ matrix.environment }}
    strategy:
      matrix:
        environment:
          - ubuntu-latest

    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Setup .NET 7.0 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Inspect code
        uses: kk-homa/resharper_inspectcode@test/uncache-action-step
        with:
          solutionPath: ./SampleDotNetProject/SampleDotNet.sln
          minimumSeverity: notice
        continue-on-error: true